config/routes.rb
Rails.application.routes.draw do
 # get 'home/top'
  get '/', to: 'home#top'
  resources :labels
  resources :pins
  resources :housepictures
  resources :houses
  resources :districts
  resources :users
  get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'

    get '/profile', to: 'users#show'
    delete '/unsubscribe', to: 'users#destroy'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/image_of_housepictures/:id', to: 'housepictures#get_image', as:'image_of_housepictures'

  get "search" => "home#search"
  root to: 'home#top'
  get "tag_search" => "home#tag_search"
end

app/models/house.rb
class House < ApplicationRecord
    belongs_to :district, optional: true
    #has_many :labels
    has_many :housepictures
    has_many :pins
    #has_many :users, through: :pins
    has_many :tag_relations
    has_many :labels, through: :tag_relations
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: %i[ show edit update destroy ]

  # GET /houses or /houses.json
  def index
    session[:selected_tikuid] ||= params[:tikuid]
    if session[:selected_tikuid].nil?
      @houses = House.all
    else
      @houses = House.where(district_id: session[:selected_tikuid])
    end
  end

  # GET /houses/1 or /houses/1.json
  def show
    @housepicture = Housepicture.new
    @housepicture.house_id =  @house.id
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses or /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to house_url(@house), notice: "House was successfully created." }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1 or /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to house_url(@house), notice: "House was successfully updated." }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1 or /houses/1.json
  def destroy
    @house.destroy

    respond_to do |format|
      format.html { redirect_to houses_url, notice: "House was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def house_params
      params.require(:house).permit(:district_id, :address, :floorplan, :age, :price, :tel, :renovation, :detail, label_ids: [])
    end
  end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= form_with(model: house) do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
        <% house.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md">
  <div class="field">
    <%= form.label "地区名" %>
    <%= form.select :district_id, District.all.map { |date| [date.name,date.id]},{}, class: "form-control" %>
  </div>
  </div>
  
  <div class="col-md">
  <div class="field">
    <%= form.label "住所" %>
    <%= form.text_field :address, class: "form-control" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md">
  <div class="field">
    <%= form.label "間取り" %>
    <%= form.text_field :floorplan, class: "form-control" %>
  </div>
  </div>

  <div class="col-md">
  <div class="field">
    <%= form.label "改装", class:"form-check-label" %>
    <div class="form-check form-switch" style="margin-top: 5px;">
    <%= form.check_box :renovation, class:"form-check-input", style:"height: 1.5em; width: 3em;" %>
  </div>
  </div>
</div>

<div class="row">
  <div class="col-md">
  <div class="field">
    <%= form.label "築年数" %>
    <%= form.number_field :age, class: "form-control" %>
  </div>
  </div>

   <div class="col-md">
   <div class="field">
    <%= form.label "TEL" %>
    <%= form.text_field :tel, class: "form-control" %>
  </div>
  </div>
</div>

<div class="row">
  <div class="col-md">
  <div class="field">
    <%= form.label "価格" %>
    <%= form.number_field :price, class: "form-control" %>
  </div>
  </div>

  <div class="col-md">
  <div class="field">
    <%= form.label "その他詳細" %>
    <%= form.text_area :detail, class: "form-control" %>
  </div>
  </div>

</div>

<div>タグ</div>
<div class="row">
 <div class="col-md">
   <%= form.collection_check_boxes(:label_ids, Label.all, :id, :tag) do |date| %>
       <%= date.label class: "form-check-label" do %>
         <%= date.check_box class: "form-check-input" %>
         <%= date.text %>
       <% end %>
       <br>
   <% end %>
 </div>
</div>


  <div class="actions">
    <%= form.submit "登録", class: "form-control btn btn-dark" %>
  </div>
<% end %>

app/views/houses/_housepicture_upload.html.erb
<%= form_with(model: housepicture) do |form| %>
  <% if housepicture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(housepicture.errors.count, "error") %> prohibited this housepicture from being saved:</h2>

      <ul>
        <% housepicture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="field">
    <%= form.label "空き家の写真を選択する" %>
    <%= form.file_field :photo, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.hidden_field :house_id %>
  </div>

  <div class="actions">
    <%= form.submit "写真をアップロードする", class: "form-control btn btn-success" %>
  </div>
<% end %>

app/views/houses/_show_template.html.erb
<p id="notice"><%= notice %></p>

<% if logged_in? %>
  <div class="row">
     <div class="col-md-2 offset-md-10">
         <% pin = Pin.where(house_id: house.id, user_id: current_user.id).first %>
         <% if pin.nil? %>
          <%= form_with(model: Pin.new) do |f| %>
            <%= f.hidden_field :house_id, :value => house.id %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.submit "ピン登録", class: "form-control btn btn-outline-primary btn-sm" %>
         <% end %>
         <% else %>
           <%= link_to 'ピン解除', pin, method: :delete, data:{ confirm:"ピン解除しますか？"}, class: "form-control btn btn-outline-dark btn sm" %>
         <% end%>
     </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-6">
    <table class="table table-hover">
<tr>
  <th>住所:</th>
  <td><%= house.address %></td>
</tr>

<tr>
  <th>間取り:</th>
  <td><%= house.floorplan %></td>
</tr>

<tr>
  <th>築年数:</th>
  <td><%= house.age %></td>
</tr>

<tr>
  <td>価格:</td>
  <td><%= house.price %></td>
</tr>

<tr>
  <td>TEL:</td>
  <td><%= house.tel %></td>
</tr>

<tr>
  <td>改装:</td>
  <td><%= house.renovation %></td>
</tr>

<tr>
  <td>その他詳細:</td>
  <td><%= house.detail %></td>
</tr>

<tr>
 <td>タグ：</td>
 <td>
   <% house.labels.each do |data| %>
      <span class="badge bg-success">
       <%= link_to data.tag, tag_search_path(selected_tag: data.id) %>
      </span>
   <%end%>
 </td>
</tr>
</table>
</div>

<div class="col-md-6">
<strong>写真:</strong>

<% house.housepictures.each do |housepicture| %>
<p>
  <%= image_tag(url_for(image_of_housepictures_path(housepicture.id)),size:'80x80') %>
<% if admin? %>
  <td><%= link_to '削除', housepicture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
</p>
<% end %>
</div>
</div>

app/views/houses/edit.html.erb
<h1>空き家情報の変更</h1>

<%= render 'form', house: @house %>

<%= link_to '詳細', @house %> |
<%= link_to '戻る', houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>空き家情報</h1>



<br>

<%  @houses.each do |house| %>
<div class="alert alert-info">
    <h4 id=<%= house.id %>>No.<%= house.id %></h4>
<%= render 'houses/show_template', house: house%>
<div class="row">
  <div class="col-md-2 offset-md-6" style="margin-top: 10px;">
    <%= link_to '詳細', house, class: "form-control btn btn-warning" %>
  </div>
  <div class="col-md-2" style="margin-top: 10px;">
  <% if admin? %>
    <%= link_to '変更',edit_house_path(house), class: "form-control btn btn-warning" %>
  <% end %>
  </div>
  <div class="col-md-2" style="margin-top: 10px;">
  <% if admin? %>
    <%= link_to '削除', house, method: :delete, data: {confirm: 'Are you sure?' },class: "form-control btn btn-warning" %>
  <% end %>
  </div>
</div>
</div>
<br><br>
<%end%>
<% if admin? %>
<%= link_to '空き家情報の追加', new_house_path, class: "form-control btn btn-dark" %>
<% end %>
<br><br>
<%= link_to 'トップに戻る' , '/', class: "form-control btn btn-light" %>

app/views/houses/new.html.erb
<h1>空き家情報の追加</h1>

<%= render 'form', house: @house %>

<%= link_to '戻る', houses_path %>

app/views/houses/show.html.erb
<%= render 'show_template', house: @house %>
<%  if admin? %>
<%= link_to '変更', edit_house_path(@house), class: "form-control btn btn-dark" %> 
<% end %>
<br><br>
<%= link_to '戻る', houses_path, class: "form-control btn btn-light" %>
<%  if admin? %>
<%= render 'housepicture_upload', housepicture: @housepicture %>
<% end %>