config/routes.rb
Rails.application.routes.draw do
 # get 'home/top'
  get '/', to: 'home#top'
  resources :labels
  resources :pins
  resources :housepictures
  resources :houses
  resources :districts
  resources :users
  get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'

    get '/profile', to: 'users#show'
    delete '/unsubscribe', to: 'users#destroy'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/image_of_housepictures/:id', to: 'housepictures#get_image', as:'image_of_housepictures'

  get "search" => "home#search"
  root to: 'home#top'
  get "tag_search" => "home#tag_search"
end

app/models/label.rb
class Label < ApplicationRecord
    #belongs_to :house ,optional: true
    has_many :tag_relations
    has_many :houses, through: :tag_relations
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: %i[ show edit update destroy ]

  # GET /labels or /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/1 or /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels or /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to label_url(@label), notice: "Label was successfully created." }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1 or /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to label_url(@label), notice: "Label was successfully updated." }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1 or /labels/1.json
  def destroy
    @label.destroy

    respond_to do |format|
      format.html { redirect_to labels_url, notice: "Label was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def label_params
      params.require(:label).permit(:tag, :house_id)
    end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_with(model: label) do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
        <% label.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag %>
  </div>

  <!--<div class="field">
    <%= form.label :house_id %>
    <%= form.number_field :house_id %>
  </div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1>タグの変更</h1>

<%= render 'form', label: @label %>

<%= link_to '詳細', @label %> |
<%= link_to '戻る', labels_path %>

app/views/labels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>タグ一覧</h1>

<table>
  <thead>
    <tr>
      <th>タグ</th>
      <!--<th>House</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.tag %></td>
        <td><%= label.house_id %></td>
        <td><%= link_to '詳細', label %></td>
        <td><%= link_to '変更', edit_label_path(label) %></td>
        <td><%= link_to '削除', label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'タグの追加', new_label_path %>
<p><%= link_to 'トップに戻る' , '/' %></p>

app/views/labels/new.html.erb
<h1>タグの追加</h1>

<%= render 'form', label: @label %>

<%= link_to '戻る', labels_path %>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @label.tag %>
</p>

<!--<p>
  <strong>House:</strong>
  <%= @label.house_id %>
</p>-->

<%= link_to '変更', edit_label_path(@label) %> |
<%= link_to '戻る', labels_path %>