config/routes.rb
Rails.application.routes.draw do
 # get 'home/top'
  get '/', to: 'home#top'
  resources :labels
  resources :pins
  resources :housepictures
  resources :houses
  resources :districts
  resources :users
  get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'

    get '/profile', to: 'users#show'
    delete '/unsubscribe', to: 'users#destroy'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/image_of_housepictures/:id', to: 'housepictures#get_image', as:'image_of_housepictures'

  get "search" => "home#search"
  root to: 'home#top'
  get "tag_search" => "home#tag_search"
end

app/models/district.rb
class District < ApplicationRecord
    has_many :houses
end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  before_action :set_district, only: %i[ show edit update destroy ]

  # GET /districts or /districts.json
  def index
    @districts = District.all
  end

  # GET /districts/1 or /districts/1.json
  def show
  end

  # GET /districts/new
  def new
    @district = District.new
  end

  # GET /districts/1/edit
  def edit
  end

  # POST /districts or /districts.json
  def create
    @district = District.new(district_params)

    respond_to do |format|
      if @district.save
        format.html { redirect_to district_url(@district), notice: "District was successfully created." }
        format.json { render :show, status: :created, location: @district }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /districts/1 or /districts/1.json
  def update
    respond_to do |format|
      if @district.update(district_params)
        format.html { redirect_to district_url(@district), notice: "District was successfully updated." }
        format.json { render :show, status: :ok, location: @district }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /districts/1 or /districts/1.json
  def destroy
    @district.destroy

    respond_to do |format|
      format.html { redirect_to districts_url, notice: "District was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_district
      @district = District.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def district_params
      params.require(:district).permit(:name)
    end
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/views/districts/_form.html.erb
<%= form_with(model: district) do |form| %>
  <% if district.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(district.errors.count, "error") %> prohibited this district from being saved:</h2>

      <ul>
        <% district.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/districts/edit.html.erb
<h1>地区情報の変更</h1>

<%= render 'form', district: @district %>

<%= link_to '詳細', @district %> |
<%= link_to '戻る', districts_path %>

app/views/districts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>地区情報</h1>

<table>
  <thead>
    <tr>
      <th>地区名</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @districts.each do |district| %>
      <tr>
        <td><%= district.name %></td>
        <td><%= link_to '詳細', district %></td>
        <td><%= link_to '変更', edit_district_path(district) %></td>
        <td><%= link_to '削除', district, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '地区情報の追加', new_district_path %>
<p><%= link_to 'トップに戻る' , '/' %></p>

app/views/districts/new.html.erb
<h1>地区情報の追加</h1>

<%= render 'form', district: @district %>

<%= link_to '戻る', districts_path %>

app/views/districts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>地区名:</strong>
  <%= @district.name %>
</p>

<%= link_to '変更', edit_district_path(@district) %> |
<%= link_to '戻る', districts_path %>