config/routes.rb
Rails.application.routes.draw do
 # get 'home/top'
  get '/', to: 'home#top'
  resources :labels
  resources :pins
  resources :housepictures
  resources :houses
  resources :districts
  resources :users
  get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'

    get '/profile', to: 'users#show'
    delete '/unsubscribe', to: 'users#destroy'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/image_of_housepictures/:id', to: 'housepictures#get_image', as:'image_of_housepictures'

  get "search" => "home#search"
  root to: 'home#top'
  get "tag_search" => "home#tag_search"
end

app/models/housepicture.rb
class Housepicture < ApplicationRecord
    belongs_to :house, optional: true
end

app/controllers/housepictures_controller.rb
class HousepicturesController < ApplicationController
  before_action :set_housepicture, only: %i[ show edit update destroy ]

  # GET /housepictures or /housepictures.json
  def index
    @housepictures = Housepicture.all
  end

  # GET /housepictures/1 or /housepictures/1.json
  def show
  end

  # GET /housepictures/new
  def new
    @housepicture = Housepicture.new
  end

  # GET /housepictures/1/edit
  def edit
  end

  # POST /housepictures or /housepictures.json
  def create
    @housepicture = Housepicture.new(housepicture_attributes)

    respond_to do |format|
      if @housepicture.save
        format.html { redirect_to house_url(@housepicture.house_id), notice: "Housepicture was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /housepictures/1 or /housepictures/1.json
  def update
    respond_to do |format|
      if @housepicture.update(housepicture_attributes)
        format.html { redirect_to housepicture_url(@housepicture), notice: "Housepicture was successfully updated." }
        format.json { render :show, status: :ok, location: @housepicture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @housepicture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /housepictures/1 or /housepictures/1.json
  def destroy
    house_id = @housepicture.house.id
    @housepicture.destroy

    respond_to do |format|
      format.html { redirect_to house_url(house_id), notice: "Housepicture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def get_image
    housepicture = Housepicture.find(params[:id])
    send_data(housepicture.photo, disposition: :inline)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_housepicture
      @housepicture = Housepicture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def housepicture_params
      params.require(:housepicture).permit(:name, :photo, :house_id)
    end

    def housepicture_attributes
      if housepicture_params[:photo].blank?
        {
          name: housepicture_params[:name], house_id: housepicture_params[:house_id]
        }
      else
      {
        name: housepicture_params[:name], photo: housepicture_params[:photo].read, house_id: housepicture_params[:house_id]
      }
      end
    end
end

app/helpers/housepictures_helper.rb
module HousepicturesHelper
end

app/views/housepictures/_form.html.erb
<%= form_with(model: housepicture) do |form| %>
  <% if housepicture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(housepicture.errors.count, "error") %> prohibited this housepicture from being saved:</h2>

      <ul>
        <% housepicture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="field">
    <%= form.label :house_id %>
    <%= form.number_field :house_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/housepictures/edit.html.erb
<h1>Editing Housepicture</h1>

<%= render 'form', housepicture: @housepicture %>

<%= link_to '詳細', @housepicture %> |
<%= link_to '戻る', housepictures_path %>

app/views/housepictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>空き家の写真</h1>

<table>
  <thead>
    <tr>
      <th>写真名</th>
      <th>写真</th>
      <th>空き家</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @housepictures.each do |housepicture| %>
      <tr>
        <td><%= housepicture.name %></td>
        <td><%= image_tag(url_for(image_of_housepictures_path(housepicture)), size:'80x80')%></td>
        <td><%= housepicture.house_id %></td>
        <td><%= link_to '詳細', housepicture %></td>
        <td><%= link_to '変更', edit_housepicture_path(housepicture) %></td>
        <td><%= link_to '削除', housepicture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '写真の新規登録', new_housepicture_path %>
<p><%= link_to 'トップに戻る' , '/' %></p>

app/views/housepictures/new.html.erb
<h1>写真の新規登録</h1>

<%= render 'form', housepicture: @housepicture %>

<%= link_to '戻る', housepictures_path %>

app/views/housepictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>写真名:</strong>
  <%= @housepicture.name %>
</p>

<p>
  <strong>写真:</strong>
  <%= image_tag(url_for(image_of_housepictures_path(@housepicture)),size:'100x100') %></td>
</p>

<p>
  <strong>空き家:</strong>
  <%= @housepicture.house_id %>
</p>

<%= link_to '変更', edit_housepicture_path(@housepicture) %> |
<%= link_to '戻る', housepictures_path %>